---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(CCA)
```

```{r}
df = read.csv("/Users/jimin/Desktop/지민/ewha/2024-1/다변량분석/통통배/dataset/hotel_bookings.csv")
head(df)
```
```{r}
df = df %>% 
        filter(rowSums(is.na(df)) == 0) %>% # 결측치 삭제(NA)
        distinct() %>% # 중복 데이터 삭제 
        filter(adults != 0) %>% # 어른이 없는 데이터 삭제 
    #    select(-agent,-company, -country) %>% # 사용하지 않을 agent, company 삭제
        mutate(reservation_status_date = as.Date(reservation_status_date)) # reservation_status_date dtype 변환

head(df)
```


## 데이터 추가 
```{r}
total_df = df %>% 
            mutate(is_prt = (country == "PRT"),
                   headcount = (adults+children+babies),
                   total_stays_night = stays_in_weekend_nights + stays_in_week_nights)

head(total_df)
```
```{r}
total_df %>% 
    ggplot() + geom_bar(aes(hotel, fill=hotel))
```

```{r}
resort_df = total_df %>% filter(hotel == "Resort Hotel")
city_df = total_df %>% filter(hotel == "City Hotel")
```

```{r}
total_df %>% select(lead_time)
```

```{r}
resort_client = resort_df %>% select(adults, children, babies, customer_type, is_prt, headcount)

resort_reservation_pattern = resort_df %>% select(is_canceled, lead_time, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, booking_changes, deposit_type, days_in_waiting_list, adr, required_car_parking_spaces, total_of_special_requests, reservation_status) # reservation_status_date

resort_lodgment = resort_df %>% select(arrival_date_year, arrival_date_month, arrival_date_week_number, total_stays_night, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, reserved_room_type, assigned_room_type, meal)

resort_reservation_route = resort_df %>% select(distribution_channel, market_segment)

```

## 사용하는 시각화용 함수들
```{r}
# 계수 시각화 
make_coef_heatmap = function(matrix){
    coef <- as.data.frame(matrix)
    coef$rownames <- rownames(coef)
    coef <- as.data.frame(coef)
    
    # 데이터프레임 melt
    coef_long <- melt(coef, id.vars = "rownames")
    
    # heatmap 그리기
    ggplot(coef_long, aes(x = variable, y = rownames, fill = value)) +
      geom_tile() +
      geom_text(aes(label = round(value, 2)), color = "black", size = 4) +
      scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0) +
      theme_minimal() +
      labs(x = "Variable", y = "Rowname", fill = "Coefficient") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
}

```

```{r}
# 상관계수 행렬 시각화 
make_corr_heatmap = function(matrix){
    corr <- as.data.frame(matrix)
    corr$rownames <- rownames(corr)
    corr <- as.data.frame(corr)
    
    # 데이터프레임 melt
    corr_long <- melt(corr, id.vars = "rownames")
    
    # heatmap 그리기
    ggplot(corr_long, aes(x = variable, y = rownames, fill = value)) +
      geom_tile() +
      geom_text(aes(label = round(value, 2)), color = "black", size = 4) +
      scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limits = c(-1, 1)) +
      theme_minimal() +
      labs(x = "Variable", y = "Rowname", fill = "Correlation") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
}
```

## CCA : 예약자와 예약 패턴

### Resort
```{r}
resort_client %>% select(customer_type) %>% table()
resort_client$customer_type = case_when(
        resort_client$customer_type == "Contract" ~ 1,
        resort_client$customer_type == "Group" ~ 2,
        resort_client$customer_type == "Transient" ~ 3,
        resort_client$customer_type == "Transient-Party" ~ 4,
        TRUE ~ NA_real_ )
resort_client
```
```{r}
resort_reservation_pattern %>% 
    select(reservation_status) %>%
    table()

resort_reservation_pattern$reservation_status = case_when(
        resort_reservation_pattern$reservation_status == "Canceled" ~ 1,
        resort_reservation_pattern$reservation_status == "Check-Out" ~ 2,
        resort_reservation_pattern$reservation_status == "No-Show" ~ 3,
        TRUE ~ NA_real_ )

resort_reservation_pattern %>% 
    select(deposit_type) %>%
    table()

resort_reservation_pattern$deposit_type = case_when(
        resort_reservation_pattern$deposit_type == "No Deposit" ~ 1,
        resort_reservation_pattern$deposit_type == "Non Refund" ~ 2,
        resort_reservation_pattern$deposit_type == "Refundable" ~ 3,
        TRUE ~ NA_real_ )

resort_reservation_pattern
```
```{r}
normalize <- function(x) {
  return((x - mean(x)) / sd(x))
}

resort_reservation_pattern = resort_reservation_pattern %>%
                                  mutate(lead_time = normalize(lead_time),
                                         adr = normalize(adr),
                                         days_in_waiting_list = normalize(days_in_waiting_list))

head(resort_reservation_pattern)
```

```{r}
cc1 = cc(resort_client[-1], resort_reservation_pattern)
```

```{r}
cc1$cor
```


```{r}
make_coef_heatmap(cc1$xcoef)
make_coef_heatmap(cc1$ycoef)
```

```{r}
make_corr_heatmap(cc1$scores$corr.X.xscores)
make_corr_heatmap(cc1$scores$corr.X.yscores)
make_corr_heatmap(cc1$scores$corr.Y.xscores)
make_corr_heatmap(cc1$scores$corr.Y.yscores)
```
```{r}
mtc = matcor(resort_client, resort_reservation_pattern)

img.matcor(mtc, type=2)
```

### City
```{r}
city_client = city_df %>% select(adults, children, babies, customer_type, is_prt, headcount)

city_reservation_pattern = city_df %>% select(is_canceled, lead_time, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, booking_changes, deposit_type, days_in_waiting_list, adr, required_car_parking_spaces, total_of_special_requests, reservation_status) # reservation_status_date

city_lodgment = city_df %>% select(arrival_date_year, arrival_date_month, arrival_date_week_number, total_stays_night, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, reserved_room_type, assigned_room_type, meal)

city_reservation_route = city_df %>% select(distribution_channel, market_segment)
```

```{r}
city_client %>% select(customer_type) %>% table()
city_client$customer_type = case_when(
        city_client$customer_type == "Contract" ~ 1,
        city_client$customer_type == "Group" ~ 2,
        city_client$customer_type == "Transient" ~ 3,
        city_client$customer_type == "Transient-Party" ~ 4,
        TRUE ~ NA_real_ )
city_client
```

```{r}
city_reservation_pattern$reservation_status = case_when(
        city_reservation_pattern$reservation_status == "Canceled" ~ 1,
        city_reservation_pattern$reservation_status == "Check-Out" ~ 2,
        city_reservation_pattern$reservation_status == "No-Show" ~ 3,
        TRUE ~ NA_real_ )

city_reservation_pattern$deposit_type = case_when(
        city_reservation_pattern$deposit_type == "No Deposit" ~ 1,
        city_reservation_pattern$deposit_type == "Non Refund" ~ 2,
        city_reservation_pattern$deposit_type == "Refundable" ~ 3,
        TRUE ~ NA_real_ )

city_reservation_pattern
```
```{r}
normalize <- function(x) {
  return((x - mean(x)) / sd(x))
}

city_reservation_pattern = city_reservation_pattern %>%
                                  mutate(lead_time = normalize(lead_time),
                                         adr = normalize(adr),
                                         days_in_waiting_list = normalize(days_in_waiting_list))

head(city_reservation_pattern)
```

```{r}
cc2 = cc(city_client[-1], city_reservation_pattern)
```

```{r}
cc2$cor
```
```{r}
make_coef_heatmap(cc2$xcoef)
make_coef_heatmap(cc2$ycoef)
```

```{r}
make_corr_heatmap(cc2$scores$corr.X.xscores)
make_corr_heatmap(cc2$scores$corr.X.yscores)
make_corr_heatmap(cc2$scores$corr.Y.xscores)
make_corr_heatmap(cc2$scores$corr.Y.yscores)
```
```{r}
mtc = matcor(city_client[-1], city_reservation_pattern)

img.matcor(mtc, type=2)
```

```{r}
plt.cc(cc1, type="i", var.label = T)
```



