---
title: "R Notebook"
output: html_notebook
---

```{r}
convert_to_numeric <- function(df, column_name, mapping) {
  # df: 데이터 프레임
  # column_name: 변환할 열 이름
  # mapping: 매핑 리스트 (예: list("No Deposit" = 1, "Non Refund" = 2, "Refundable" = 3))
  
  # 매핑 리스트를 숫자 벡터로 변환
  mapping <- unlist(mapping)
  
  df <- df %>%
    mutate(!!sym(column_name) := case_when(
      !!sym(column_name) %in% names(mapping) ~ mapping[!!sym(column_name)],
      TRUE ~ NA_real_
    ))
  
  return(df)
}
```

```{r}
library(tidyverse)
library(CCA)
library(corrplot)
library(reshape)
```

```{r}
df = read.csv("/Users/jimin/Desktop/지민/ewha/2024-1/다변량분석/통통배/dataset/hotel_bookings.csv")
head(df)
```

## 전처리 
```{r}
total_df = df %>% 
            filter(rowSums(is.na(df)) == 0) %>% # 결측치 삭제(NA)
                distinct() %>% # 중복 데이터 삭제 
                filter(adults != 0) %>% # 어른이 없는 데이터 삭제 
                mutate(reservation_status_date = as.Date(reservation_status_date),
                       is_prt = (country == "PRT"),
                       headcount = (adults+children+babies),
                       total_stays_night = stays_in_weekend_nights + stays_in_week_nights,
                       childrens = children+babies) %>%
                mutate(have_baby = (childrens != 0)) %>% 
                dplyr::select(-country,-agent,-company, -childrens, -children, -babies) %>% 
                filter(adults <= 10) %>% 
                filter(total_stays_night != 0) 
```

```{r}
total_df
```


headcount 기준으로 10명 넘는 애들은 좀 다른 애들도 있는데,
adult는 걍 ㅈㄴ 수상함 이래저래

## dummy variable
```{r}
total_df = convert_to_numeric(total_df, 
                              "customer_type", 
                              list("Contract" = 1, "Group" = 2, "Transient" = 3, "Transient-Party" = 4))

total_df = convert_to_numeric(total_df, 
                              "reservation_status", 
                              list("Canceled" = 1, "Check-Out" = 2, "No-Show" = 3))

total_df = convert_to_numeric(total_df, 
                              "deposit_type", 
                              list("No Deposit" = 1, "Non Refund" = 2, "Refundable" = 3))

total_df = convert_to_numeric(total_df, 
                              "arrival_date_month", 
                              list(
                                  "January" = 1, "February" = 2, "March" = 3, "April" = 4,
                                  "May" = 5, "June" = 6, "July" = 7, "August" = 8,
                                  "September" = 9, "October" = 10, "November" = 11, "December" = 12
                                ))

total_df = convert_to_numeric(total_df, 
                              "meal", 
                              list("BB" = 1, "FB" = 2, "HB" = 3, "SC" = 4, "Undefined" = 5))

total_df = convert_to_numeric(total_df, 
                              "market_segment", 
                              list("Aviation" = 1, "Complementary" = 2, "Corporate" = 3, 
                                   "Direct" = 4, "Groups" = 5, "Offline TA/TO" = 6, "Online TA" = 7))

total_df = convert_to_numeric(total_df, 
                              "distribution_channel", 
                              list("Corporate" = 1, "Direct" = 2, "GDS" = 3, "TA/TO" = 4, "Undefined" = 5))

total_df = convert_to_numeric(total_df, 
                              "reserved_room_type", 
                              list("A" = 1, "B" = 2, "C" = 3, "D" = 4, "E" = 5, "F" = 6, "G" = 7, "H" = 8, "L" = 11))

total_df = convert_to_numeric(total_df, 
                              "assigned_room_type", 
                              list("A" = 1, "B" = 2, "C" = 3, "D" = 4, "E" = 5, "F" = 6, "G" = 7, "H" = 8, "I" = 9, "K" = 10, "L" = 11))

head(total_df)

dim(total_df)
```


## correlation
```{r}
total_df %>%
    dplyr::select(-hotel,-reservation_status_date) %>%
    cor() %>% 
    corrplot()
```

## split df per resort city 
```{r}
resort_df = total_df %>% filter(hotel == "Resort Hotel")
city_df = total_df %>% filter(hotel == "City Hotel")
```

```{r}
resort_client = resort_df %>% dplyr::select(have_baby, customer_type, is_prt, headcount)

resort_reservation_pattern = resort_df %>% dplyr::select(is_canceled, lead_time, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, booking_changes, deposit_type, days_in_waiting_list, adr, required_car_parking_spaces, total_of_special_requests, reservation_status) # reservation_status_date

resort_lodgment = resort_df %>% dplyr::select(arrival_date_year, arrival_date_month, arrival_date_week_number, total_stays_night, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, reserved_room_type, assigned_room_type, meal)

resort_reservation_route = resort_df %>% dplyr::select(distribution_channel, market_segment)
```

```{r}
city_client = city_df %>% dplyr::select(have_baby, customer_type, is_prt, headcount)

city_reservation_pattern = city_df %>% dplyr::select(is_canceled, lead_time, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, booking_changes, deposit_type, days_in_waiting_list, adr, required_car_parking_spaces, total_of_special_requests, reservation_status) # reservation_status_date

city_lodgment = city_df %>% dplyr::select(arrival_date_year, arrival_date_month, arrival_date_week_number, total_stays_night, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, reserved_room_type, assigned_room_type, meal)

city_reservation_route = city_df %>% dplyr::select(distribution_channel, market_segment)
```

### 사용하는 함수 
```{r}
normalize <- function(x) {
  return((x - mean(x)) / sd(x))
}
```

```{r}
# 계수 시각화 
make_coef_heatmap = function(matrix){
    coef <- as.data.frame(matrix)
    coef$rownames <- rownames(coef)
    coef <- as.data.frame(coef)
    
    # 데이터프레임 melt
    coef_long <- melt(coef, id.vars = "rownames")
    
    # heatmap 그리기
    ggplot(coef_long, aes(x = variable, y = rownames, fill = value)) +
      geom_tile() +
      geom_text(aes(label = round(value, 2)), color = "black", size = 4) +
      scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0) +
      theme_minimal() +
      labs(x = "Variable", y = "Rowname", fill = "Coefficient") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
}

```

```{r}
# 상관계수 행렬 시각화 
make_corr_heatmap = function(matrix){
    corr <- as.data.frame(matrix)
    corr$rownames <- rownames(corr)
    corr <- as.data.frame(corr)
    
    # 데이터프레임 melt
    corr_long <- melt(corr, id.vars = "rownames")
    
    # heatmap 그리기
    ggplot(corr_long, aes(x = variable, y = rownames, fill = value)) +
      geom_tile() +
      geom_text(aes(label = round(value, 2)), color = "black", size = 4) +
      scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limits = c(-1, 1)) +
      theme_minimal() +
      labs(x = "Variable", y = "Rowname", fill = "Correlation") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
}
```

## Resort
### Normalized
```{r}
normalized_resort_client = data.frame(apply(resort_client, MARGIN=2, FUN=normalize))
normalized_resort_reservation_pattern = data.frame(apply(resort_reservation_pattern, MARGIN=2, FUN=normalize))
```

### CCA
```{r}
x = normalized_resort_client
y = normalized_resort_reservation_pattern %>% dplyr::select(-days_in_waiting_list)

cc1 = cc(x, y)
```

```{r}
cc1$cor 
```

```{r}
make_coef_heatmap(cc1$xcoef)
make_coef_heatmap(cc1$ycoef)
```
```{r}
make_corr_heatmap(cc1$scores$corr.X.xscores)
make_corr_heatmap(cc1$scores$corr.X.yscores)
make_corr_heatmap(cc1$scores$corr.Y.xscores)
make_corr_heatmap(cc1$scores$corr.Y.yscores)
```

```{r}
mtc = matcor(x,y)

img.matcor(mtc, type=1)
```
## City
### Normalized
```{r}
normalized_city_client = data.frame(apply(city_client, MARGIN=2, FUN=normalize))
normalized_city_reservation_pattern = data.frame(apply(city_reservation_pattern, MARGIN=2, FUN=normalize))
```

### CCA
```{r}
x = normalized_city_client 
y = normalized_city_reservation_pattern  %>% dplyr::select(-days_in_waiting_list)

cc2 = cc(x, y)
cc2$cor
```


```{r}
make_coef_heatmap(cc2$xcoef)
make_coef_heatmap(cc2$ycoef)
```
```{r}
make_corr_heatmap(cc2$scores$corr.X.xscores)
make_corr_heatmap(cc2$scores$corr.X.yscores)
make_corr_heatmap(cc2$scores$corr.Y.xscores)
make_corr_heatmap(cc2$scores$corr.Y.yscores)
```

```{r}
U1 = cc1$scores$xscores[,1]
V1 = cc1$scores$yscores[,1]

ddf = data.frame(U1,V1) %>% filter(V1 > -10)
ggplot(ddf, aes(U1,V1)) + geom_point()
```

```{r}
plt.cc(cc1, type="b", var.label = T)
```
```{r}
mtc = matcor(normalized_city_client[-1], normalized_city_reservation_pattern)

img.matcor(mtc, type=2)
```