---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(fastcluster)
library(MASS)
library(caret)
```

```{r}
make_mean_heatmap = function(matrix){
    corr <- as.data.frame(matrix)
    corr$rownames <- rownames(corr)
    corr <- as.data.frame(corr)
    
    # 데이터프레임 melt
    corr_long <- melt(corr, id.vars = "rownames")
    
    # heatmap 그리기
    ggplot(corr_long, aes(x = variable, y = rownames, fill = value)) +
      geom_tile() +
      geom_text(aes(label = round(value, 2)), color = "black", size = 4) +
      scale_fill_gradient2(low = "white", high = "#FF69B4", mid = "#FFC0CB") +
      theme_minimal() +
      labs(x = "Variable", y = "Rowname", fill = "value") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
}
```

```{r}
split_data <- function(data, train_ratio = 0.7, seed = NULL) {
  if (!is.null(seed)) {
    set.seed(seed)
  }
  
  # 인덱스를 사용하여 데이터를 나눕니다
  train_index <- createDataPartition(data[[1]], p = train_ratio, list = FALSE)
  
  train_set <- data[train_index, ]
  test_set <- data[-train_index, ]
  
  return(list(train = train_set, test = test_set))
}
```

```{r}
boolean_palette = c("TRUE"="#FF3366",
                    "FALSE"="#6699FF",
                    "1"="#FF3366",
                    "0"="#6699FF")
```

```{r}
df = read.csv("/Users/jimin/Desktop/지민/ewha/2024-1/다변량분석/통통배/dataset/hotel_bookings.csv")
head(df)
```

## 전처리 
```{r}
total_df = df %>% 
            filter(rowSums(is.na(df)) == 0) %>% # 결측치 삭제(NA)
                distinct() %>% # 중복 데이터 삭제 
                filter(adults != 0) %>% # 어른이 없는 데이터 삭제 
                mutate(reservation_status_date = as.Date(reservation_status_date),
                       is_prt = (country == "PRT"),
                       headcount = (adults+children+babies),
                       total_stays_night = stays_in_weekend_nights + stays_in_week_nights,
                       childrens = children+babies) %>%
                mutate(have_baby = (childrens != 0)) %>% 
                dplyr::select(-country,-agent,-company, -childrens, -children, -babies) %>% 
                filter(adults <= 10) %>% 
                filter(total_stays_night != 0) 
```

## to dummy variable 
```{r}
total_df = convert_to_numeric(total_df, 
                              "customer_type", 
                              list("Contract" = 1, "Group" = 2, "Transient" = 3, "Transient-Party" = 4))

total_df = convert_to_numeric(total_df, 
                              "reservation_status", 
                              list("Canceled" = 1, "Check-Out" = 2, "No-Show" = 3))

total_df = convert_to_numeric(total_df, 
                              "deposit_type", 
                              list("No Deposit" = 1, "Non Refund" = 2, "Refundable" = 3))

total_df = convert_to_numeric(total_df, 
                              "arrival_date_month", 
                              list(
                                  "January" = 1, "February" = 2, "March" = 3, "April" = 4,
                                  "May" = 5, "June" = 6, "July" = 7, "August" = 8,
                                  "September" = 9, "October" = 10, "November" = 11, "December" = 12
                                ))

total_df = convert_to_numeric(total_df, 
                              "meal", 
                              list("BB" = 1, "FB" = 2, "HB" = 3, "SC" = 4, "Undefined" = 5))

total_df = convert_to_numeric(total_df, 
                              "market_segment", 
                              list("Aviation" = 1, "Complementary" = 2, "Corporate" = 3, 
                                   "Direct" = 4, "Groups" = 5, "Offline TA/TO" = 6, "Online TA" = 7))

total_df = convert_to_numeric(total_df, 
                              "distribution_channel", 
                              list("Corporate" = 1, "Direct" = 2, "GDS" = 3, "TA/TO" = 4, "Undefined" = 5))

total_df = convert_to_numeric(total_df, 
                              "reserved_room_type", 
                              list("A" = 1, "B" = 2, "C" = 3, "D" = 4, "E" = 5, "F" = 6, "G" = 7, "H" = 8, "L" = 11))

total_df = convert_to_numeric(total_df, 
                              "assigned_room_type", 
                              list("A" = 1, "B" = 2, "C" = 3, "D" = 4, "E" = 5, "F" = 6, "G" = 7, "H" = 8, "I" = 9, "K" = 10, "L" = 11))
```

```{r}
total_df %>% is.na() %>% sum()
```

## split df per resort city 
```{r}
resort_df = total_df %>% filter(hotel == "Resort Hotel")
city_df = total_df %>% filter(hotel == "City Hotel")
```

```{r}
resort_client = resort_df %>% dplyr::select(have_baby, customer_type, is_prt, headcount)

resort_reservation_pattern = resort_df %>% dplyr::select(is_canceled, lead_time, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, booking_changes, deposit_type, days_in_waiting_list, adr, required_car_parking_spaces, total_of_special_requests, reservation_status) # reservation_status_date
```

```{r}
city_client = city_df %>% dplyr::select(have_baby, customer_type, is_prt, headcount)

city_reservation_pattern = city_df %>% dplyr::select(is_canceled, lead_time, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, booking_changes, deposit_type, days_in_waiting_list, adr, required_car_parking_spaces, total_of_special_requests, reservation_status) # reservation_status_date
```

## 01. resort
## LDA 
- 호텔 별로 가격대 분리 
```{r}
total_df %>% 
  filter(hotel == "Resort Hotel") %>% 
  filter(adr >= 0 ) %>%
  filter(is_canceled == 0 ) %>%
  mutate(adr_group = cut(adr, breaks = quantile(adr, probs = seq(0, 1, by = 1/3)), 
                         include.lowest = TRUE, labels = c("Low", "Medium", "High"))) %>%
  group_by(adr_group) %>%
  summarise(min_val = min(adr),
            max_val = max(adr),
            mean_val = mean(adr), 
            .groups = 'drop') %>%
  ggplot() + 
  geom_segment(aes(x = adr_group, xend = adr_group, y = 0, yend = min_val)) +
    
    geom_point(aes(x = adr_group, y = min_val), 
               size = 5, color = "red", fill = alpha("orange", 0.3), alpha = 0.7, shape = 21, stroke = 2) +
    geom_text(aes(x = adr_group, y = min_val, label = round(min_val, 2)), hjust = 1.5) + 
    
    geom_point(aes(x = adr_group, y = mean_val), 
             size = 5, color = "blue", fill = alpha("orange", 0.3), alpha = 0.7, shape = 21, stroke = 2) +
    geom_text(aes(x = adr_group, y = mean_val, label = round(mean_val, 2)), hjust = 1.5) +  
    
  labs(x = "ADR Group", y = "Average ADR", title = "Min, Average ADR for Resort Hotel") +
  theme_minimal()
```

```{r}
resort = total_df %>% 
              filter(hotel == "Resort Hotel") %>% 
              filter(adr >= 0 ) %>%
              filter(is_canceled == 0 ) %>%
            #  mutate(lead_time = normalize(lead_time)) %>% 
              mutate(adr_group = cut(adr, breaks = quantile(adr, probs = seq(0, 1, by = 1/3)), 
                         include.lowest = TRUE, labels = c("Low", "Medium", "High"))) %>%
              dplyr::select(adr_group, have_baby, is_prt, headcount, stays_in_weekend_nights, total_stays_night, lead_time, arrival_date_month) #, reserved_room_type

head(resort)
```

```{r}
split = split_data(resort, train_ratio = 0.8)

train_dataset = split$train
test_dataset = split$test
```

```{r}
normalized_resort = data.frame(apply(resort[-c(1)], MARGIN=2, FUN=normalize))
normalized_resort$adr_group = resort$adr_group

split = split_data(normalized_resort, train_ratio = 0.8) #

train_dataset = split$train
test_dataset = split$test
```

```{r}
resort %>% 
    dplyr::select(adr_group) %>%
    table()

train_dataset %>% 
    dplyr::select(adr_group) %>%
    table()

test_dataset %>% 
    dplyr::select(adr_group) %>%
    table()
```

```{r}
ld.result = lda(adr_group~. , data = train_dataset)
ld.result
```
```{r}
pred = predict(ld.result, train_dataset)$class
mean(train_dataset$adr_group == pred)
mean(train_dataset$adr_group != pred)
```
```{r}
pred = predict(ld.result, test_dataset)$class
mean(test_dataset$adr_group == pred)
mean(test_dataset$adr_group != pred)
```

```{r}
pred <- predict(ld.result, test_dataset)$class

# 실제 값과 예측 값을 결합한 데이터 프레임 생성
comparison_df <- data.frame(Predicted = pred, Actual = test_dataset$adr_group)

# 교차표 생성
confusion_matrix <- table(comparison_df$Actual, comparison_df$Predicted)

# 교차표를 데이터 프레임으로 변환
confusion_df <- as.data.frame(confusion_matrix)
colnames(confusion_df) <- c("Actual", "Predicted", "Freq")

# 히트맵 생성
ggplot(confusion_df, aes(x = Actual, y = Predicted, fill = Freq)) +
  geom_tile(color = "white") +
  geom_text(aes(label = Freq), vjust = 1) +
  scale_fill_gradient(low = "white", high = "skyblue") +
  labs(x = "Actual ADR Group", y = "Predicted ADR Group", title = "Confusion Matrix Heatmap") +
  theme_minimal()
```
```{r}
make_mean_heatmap(ld.result$means)
make_coef_heatmap(ld.result$scaling)
```

- 
## 02. CITY
```{r}
total_df %>% 
  filter(hotel == "City Hotel") %>% 
  filter(adr >= 0 ) %>% 
  filter(is_canceled == 0) %>%
  mutate(adr_group = cut(adr, breaks = quantile(adr, probs = seq(0, 1, by = 1/3)), 
                         include.lowest = TRUE, labels = c("Low", "Medium", "High"))) %>%
  group_by(adr_group) %>%
  summarise(min_val = min(adr),
            max_val = max(adr),
            mean_val = mean(adr), 
            .groups = 'drop') %>%
  ggplot() + 
  geom_segment(aes(x = adr_group, xend = adr_group, y = 0, yend = min_val)) +
    
    geom_point(aes(x = adr_group, y = min_val), 
               size = 5, color = "red", fill = alpha("orange", 0.3), alpha = 0.7, shape = 21, stroke = 2) +
    geom_text(aes(x = adr_group, y = min_val, label = round(min_val, 2)), hjust = 1.5) + 
    
    geom_point(aes(x = adr_group, y = mean_val), 
             size = 5, color = "blue", fill = alpha("orange", 0.3), alpha = 0.7, shape = 21, stroke = 2) +
    geom_text(aes(x = adr_group, y = mean_val, label = round(mean_val, 2)), hjust = 1.5) +  
    
  labs(x = "ADR Group", y = "Average ADR", title = "Min, Average ADR for City Hotel") +
  theme_minimal()
```

```{r}
city = total_df %>% 
              filter(hotel == "City Hotel") %>% 
              filter(adr >= 0 ) %>%
              filter(is_canceled == 0) %>%
              mutate(adr_group = cut(adr, breaks = quantile(adr, probs = seq(0, 1, by = 1/3)), 
                         include.lowest = TRUE, labels = c("Low", "Medium", "High"))) %>%
              dplyr::select(adr_group, have_baby, is_prt, headcount, stays_in_weekend_nights, total_stays_night, lead_time)

head(city)
```
```{r}
normalized_city = data.frame(apply(city[-c(1)], MARGIN=2, FUN=normalize))
normalized_city$adr_group = city$adr_group

split = split_data(normalized_city, train_ratio = 0.8) 

train_dataset = split$train
test_dataset = split$test
```

```{r}
split = split_data(city, train_ratio = 0.8)

train_dataset = split$train
test_dataset = split$test
```

```{r}
resort %>% 
    dplyr::select(adr_group) %>%
    table()

train_dataset %>% 
    dplyr::select(adr_group) %>%
    table()

test_dataset %>% 
    dplyr::select(adr_group) %>%
    table()
```

```{r}
ld.result = lda(adr_group~. , data = train_dataset)
ld.result
```
```{r}
pred = predict(ld.result, train_dataset)$class
mean(train_dataset$adr_group == pred)
mean(train_dataset$adr_group != pred)
```
```{r}
pred = predict(ld.result, test_dataset)$class
mean(test_dataset$adr_group == pred)
mean(test_dataset$adr_group != pred)
```

```{r}
pred <- predict(ld.result, test_dataset)$class

# 실제 값과 예측 값을 결합한 데이터 프레임 생성
comparison_df <- data.frame(Predicted = pred, Actual = test_dataset$adr_group)

# 교차표 생성
confusion_matrix <- table(comparison_df$Actual, comparison_df$Predicted)

# 교차표를 데이터 프레임으로 변환
confusion_df <- as.data.frame(confusion_matrix)
colnames(confusion_df) <- c("Actual", "Predicted", "Freq")

# 히트맵 생성
ggplot(confusion_df, aes(x = Actual, y = Predicted, fill = Freq)) +
  geom_tile(color = "white") +
  geom_text(aes(label = Freq), vjust = 1) +
  scale_fill_gradient(low = "white", high = "skyblue") +
  labs(x = "Actual ADR Group", y = "Predicted ADR Group", title = "Confusion Matrix Heatmap") +
  theme_minimal()
```
```{r}
make_mean_heatmap(ld.result$means)
make_coef_heatmap(ld.result$scaling)
```
## 그룹을 기준으로 나누기 
### Resort
```{r}
resort = total_df %>% 
              filter(hotel == "Resort Hotel") %>% 
              filter(adr >= 0 ) %>%
              filter(is_canceled == 0 ) %>%
            #  mutate(lead_time = normalize(lead_time)) %>% 
              mutate(adr_group = cut(adr, breaks = quantile(adr, probs = seq(0, 1, by = 1/3)), 
                         include.lowest = TRUE, labels = c("Low", "Medium", "High"))) %>%
              dplyr::select(adr_group, adr, arrival_date_month, headcount, stays_in_weekend_nights, total_stays_night, reserved_room_type)  # reserved_room_type을 추가

head(resort)
```
```{r}
resort %>% 
    ggplot(aes(adr_group, adr)) + 
    geom_jitter(aes(color=adr_group), size=0.01) + 
    geom_boxplot(aes(fill=adr_group)) + 
    facet_wrap(~reserved_room_type)
    
```
```{r}
normalized_resort = data.frame(apply(resort[-c(1)], MARGIN=2, FUN=normalize))
normalized_resort$adr_group = resort$adr_group

split = split_data(normalized_resort, train_ratio = 0.8) 

train_dataset = split$train
test_dataset = split$test
```


```{r}
ld.result = lda(adr_group~. , data = train_dataset)
ld.result
```
```{r}
pred = predict(ld.result, train_dataset)$class
mean(train_dataset$adr_group == pred)
mean(train_dataset$adr_group != pred)
```
```{r}
pred = predict(ld.result, test_dataset)$class
mean(test_dataset$adr_group == pred)
mean(test_dataset$adr_group != pred)
```

```{r}
pred <- predict(ld.result, test_dataset)$class

# 실제 값과 예측 값을 결합한 데이터 프레임 생성
comparison_df <- data.frame(Predicted = pred, Actual = test_dataset$adr_group)

# 교차표 생성
confusion_matrix <- table(comparison_df$Actual, comparison_df$Predicted)

# 교차표를 데이터 프레임으로 변환
confusion_df <- as.data.frame(confusion_matrix)
colnames(confusion_df) <- c("Actual", "Predicted", "Freq")

# 히트맵 생성
ggplot(confusion_df, aes(x = Actual, y = Predicted, fill = Freq)) +
  geom_tile(color = "white") +
  geom_text(aes(label = Freq), vjust = 1) +
  scale_fill_gradient(low = "white", high = "skyblue") +
  labs(x = "Actual ADR Group", y = "Predicted ADR Group", title = "Confusion Matrix Heatmap") +
  theme_minimal()
```
```{r}
make_mean_heatmap(ld.result$means)
make_coef_heatmap(ld.result$scaling)
```
```{r}
# 예시
valid = test_dataset[23,-1]

valid_df <- valid[rep(1, 11), ] %>%
  mutate(reserved_room_type = 1:11)

valid
valid_df[-c(9,10),]
predict(ld.result, valid_df[-c(9,10),])$class
```
### City
```{r}
city = total_df %>% 
              filter(hotel == "City Hotel") %>% 
              filter(is_canceled == 0 ) %>%
              filter(adr <= 4000) %>%
            #  mutate(lead_time = normalize(lead_time)) %>% 
              mutate(adr_group = cut(adr, breaks = quantile(adr, probs = seq(0, 1, by = 1/3)), 
                         include.lowest = TRUE, labels = c("Low", "Medium", "High"))) %>%
              dplyr::select(adr_group, adr, arrival_date_month, headcount, stays_in_weekend_nights, total_stays_night, reserved_room_type)  # reserved_room_type을 추가

head(city)
```
```{r}
city %>% 
    ggplot(aes(adr_group, adr)) + 
    geom_jitter(aes(color=adr_group), size=0.01) + 
    geom_boxplot(aes(fill=adr_group)) + 
    facet_wrap(~reserved_room_type)
    
```
```{r}
city %>% 
    ggplot(aes(adr_group, adr)) + 
    geom_jitter(aes(color=adr_group), size=0.01) + 
    geom_boxplot(aes(fill=adr_group)) + 
    facet_wrap(~arrival_date_month)
```

```{r}
normalized_city = data.frame(apply(city[-c(1)], MARGIN=2, FUN=normalize))
normalized_city$adr_group = city$adr_group

#split = split_data(normalized_city, train_ratio = 0.8) #
split = split_data(city, train_ratio = 0.8) 

train_dataset = split$train
test_dataset = split$test
```


```{r}
ld.result = lda(adr_group~. , data = train_dataset)
ld.result
```
```{r}
pred = predict(ld.result, train_dataset)$class
mean(train_dataset$adr_group == pred)
mean(train_dataset$adr_group != pred)
```
```{r}
pred = predict(ld.result, test_dataset)$class
mean(test_dataset$adr_group == pred)
mean(test_dataset$adr_group != pred)
```

```{r}
pred <- predict(ld.result, test_dataset)$class

# 실제 값과 예측 값을 결합한 데이터 프레임 생성
comparison_df <- data.frame(Predicted = pred, Actual = test_dataset$adr_group)

# 교차표 생성
confusion_matrix <- table(comparison_df$Actual, comparison_df$Predicted)

# 교차표를 데이터 프레임으로 변환
confusion_df <- as.data.frame(confusion_matrix)
colnames(confusion_df) <- c("Actual", "Predicted", "Freq")

# 히트맵 생성
ggplot(confusion_df, aes(x = Actual, y = Predicted, fill = Freq)) +
  geom_tile(color = "white") +
  geom_text(aes(label = Freq), vjust = 1) +
  scale_fill_gradient(low = "white", high = "skyblue") +
  labs(x = "Actual ADR Group", y = "Predicted ADR Group", title = "Confusion Matrix Heatmap") +
  theme_minimal()
```
```{r}
make_mean_heatmap(ld.result$means)
make_coef_heatmap(ld.result$scaling)
```
```{r}
# 예시
valid = test_dataset[291,]

valid_df <- valid[rep(1, 11), ] %>%
  mutate(reserved_room_type = 1:11)

predict(ld.result, valid_df[-c(9,10),])$class
```

